version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: ./application/environments/local/mysql/Dockerfile
    container_name: falcon_mysql
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ckBuZG9tcDRzc3dvcmQK
      MYSQL_USER: falcon
      MYSQL_PASSWORD: falcon
      MYSQL_DATABASE: falcon
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  mysql_backup:
    build:
      context: .
      dockerfile: ./application/environments/local/mysql/backup/Dockerfile
    container_name: falcon_mysql_backup
    command: sh -c '/wait-for mysql:3306 -t 100 -- /scripts/startup.sh restore'
    volumes:
      - ./application/environments/local/mysql/backup:/backup
    links:
      - "mysql"
    depends_on:
      - "mysql"
    restart: on-failure
    environment:
      MYSQL_DATABASE: falcon
      MYSQL_ROOT_PASSWORD: ckBuZG9tcDRzc3dvcmQK

  api:
    build:
      context: .
      dockerfile: ./application/environments/local/app/Dockerfile
    container_name: falcon_api
    command: sh -c '/wait-for mysql:3306 -t 100 -- /scripts/startup.sh'
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - "mysql"
    depends_on:
      - "mysql_backup"
    restart: on-failure
    environment:
      APP_ENVIRONMENT: development
      APP_JWT_SECRET: qwertyuiopasdfghjklzxcvbnm123456
      APP_DB_HOST: mysql
      APP_DB_PORT: 3306
      APP_DB_USER: falcon
      APP_DB_PASSWORD: falcon
      APP_DB_DATABASE: falcon


volumes:
  db_data:
