version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: ./application/environments/local/mysql/Dockerfile
    container_name: falcon_mysql
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ckBuZG9tcDRzc3dvcmQK
      MYSQL_USER: falcon
      MYSQL_PASSWORD: falcon
      MYSQL_DATABASE: falcon
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  mysql_seed:
    build:
      context: .
      dockerfile: ./application/environments/local/mysql/seed/Dockerfile
    container_name: falcon_mysql_seed
    command: sh -c '/wait-for mysql:3306 -t 100 -- /scripts/startup.sh'
    volumes:
      - ./application/environments/local/mysql/seed:/seed
    links:
      - "mysql"
    depends_on:
      - "mysql"
    restart: on-failure
    environment:
      MYSQL_DATABASE: falcon
      MYSQL_ROOT_PASSWORD: ckBuZG9tcDRzc3dvcmQK

  mongo:
    build:
      context: .
      dockerfile: ./application/environments/local/mongo/Dockerfile
    container_name: falcon_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: on-failure

  mongo_seed:
    build:
      context: .
      dockerfile: ./application/environments/local/mongo/seed/Dockerfile
    container_name: falcon_mongo_seed
    command: sh -c '/wait-for mongo:27017 -t 100 -- /scripts/startup.sh'
    volumes:
      - ./application/environments/local/mongo/seed:/seed
    links:
      - "mongo"
    depends_on:
      - "mongo"
    restart: on-failure
    environment:
      MONGODB_DATABASE: falcon

  api:
    build:
      context: .
      dockerfile: ./application/environments/local/app/Dockerfile
    container_name: falcon_api
    command: sh -c '/wait-for mysql:3306 -t 100 -- /scripts/startup.sh'
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - "mysql"
      - "mongo"
    depends_on:
      - "mysql"
    restart: on-failure
    environment:
      APP_ENVIRONMENT: development
      APP_JWT_SECRET: qwertyuiopasdfghjklzxcvbnm123456
      APP_RELATIONAL_DATA: mysql
      APP_RELATIONAL_DATA_HOST: mysql
      APP_RELATIONAL_DATA_PORT: 3306
      APP_RELATIONAL_DATA_USER: falcon
      APP_RELATIONAL_DATA_PASSWORD: falcon
      APP_RELATIONAL_DATA_DATABASE: falcon
      APP_DOCUMENT_DATA: mongodb
      APP_DOCUMENT_DATA_HOST: mongo
      APP_DOCUMENT_DATA_PORT: 27017
      PYTHONUNBUFFERED: 'TRUE'


volumes:
  mysql_data:
  mongo_data:
